# Generated by Django 4.2.7 on 2023-12-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='app_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='app',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
