# Generated by Django 4.2.7 on 2023-12-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapps', '0002_rename_app_name_app_name_app_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.CharField(default='Application description', max_length=250),
        ),
    ]
